# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install Bazelisk
        run: |
          wget https://github.com/bazelbuild/bazelisk/releases/download/v1.6.0/bazelisk-linux-amd64
          echo "616f65bcdcfd134a19d5d86c591c35098d7732be26145bf06f02ec9e3e52700c bazelisk-linux-amd64" | sha256sum --check
          mkdir -p "${GITHUB_WORKSPACE}/bin/"
          sudo mv bazelisk-linux-amd64 ${GITHUB_WORKSPACE}/bin/bazelisk
          chmod +x ${GITHUB_WORKSPACE}/bin/bazelisk
      - name: Build sources
        run: | 
          "${GITHUB_WORKSPACE}/bin/bazelisk" build //src/...
  # This workflow contains a single job called "build"
  formatting:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install Bazelisk
        run: |
          wget https://github.com/bazelbuild/bazelisk/releases/download/v1.6.0/bazelisk-linux-amd64
          echo "616f65bcdcfd134a19d5d86c591c35098d7732be26145bf06f02ec9e3e52700c bazelisk-linux-amd64" | sha256sum --check
          mkdir -p "${GITHUB_WORKSPACE}/bin/"
          sudo mv bazelisk-linux-amd64 ${GITHUB_WORKSPACE}/bin/bazelisk
          chmod +x ${GITHUB_WORKSPACE}/bin/bazelisk
      - name: "Check Bazel build file formatting"
        run: | 
          "${GITHUB_WORKSPACE}/bin/bazelisk" run buildifier_check
      - name: "Kotlin file format checks"
        run: |   
          "${GITHUB_WORKSPACE}/bin/bazelisk" run ktlint_check
      - name: "Intellij formatter"
        run: |
          "${GITHUB_WORKSPACE}/bin/bazelisk" run intellij_check
      - name: "Add license check"
        run: | 
          "${GITHUB_WORKSPACE}/bin/bazelisk" run addlicense_check
  testing:
    runs-on: ubuntu-latest
    
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - uses: actions/checkout@v2
      - name: Install Bazelisk
        run: |
          wget https://github.com/bazelbuild/bazelisk/releases/download/v1.6.0/bazelisk-linux-amd64
          echo "616f65bcdcfd134a19d5d86c591c35098d7732be26145bf06f02ec9e3e52700c bazelisk-linux-amd64" | sha256sum --check
          mkdir -p "${GITHUB_WORKSPACE}/bin/"
          sudo mv bazelisk-linux-amd64 ${GITHUB_WORKSPACE}/bin/bazelisk
          chmod +x ${GITHUB_WORKSPACE}/bin/bazelisk
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: "Unit Tests"
        run: |
          "${GITHUB_WORKSPACE}/bin/bazelisk" run test //src/test/...
