# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Mount bazel cache
        uses: actions/cache@v1
        with:
          path: "/home/runner/.cache/bazel"
          key: bazel
      - name: Install Bazelisk
        run: |
          wget https://github.com/bazelbuild/bazelisk/releases/download/v1.6.0/bazelisk-linux-amd64
          echo "616f65bcdcfd134a19d5d86c591c35098d7732be26145bf06f02ec9e3e52700c bazelisk-linux-amd64" | sha256sum --check
          sudo mv bazelisk-linux-amd64 /usr/bin/bazelisk
          chmod +x /usr/bin/bazelisk
      - name: Build sources
        run: bazelisk build //src/...
  # This workflow contains a single job called "build"
  formatting:
      needs: build
      runs-on: ubuntu-latest
      steps:
        - name: "Check Bazel build file formatting"
          run: bazelisk run buildifier_check
        - name: "Kotlin file format checks"
          run: bazelisk run ktlint_check
        - name: "Intellij formatter"
          run: bazelisk run intellij_check
        - name: "Add license check"
          run: bazelisk run addlicense_check
  testing:
    needs: build
    runs-on: ubuntu-lates
    
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - name: "Unit Tests"
      run: bazelisk test //src/test/...
